site_name: Simnibs Cifti Tools 
theme: material

plugins:
    - search
nav:
- Project Overview: project_overview.md 
- Installation and set-up: Installation and set-up.md 
- Required Imaging Files: dependancies.md
- Arguments and Flags: args_flags.md
- Efield Generator: Efield_generator.md
- Utilities: Utilities.md 
- FAQ: FAQ.md
- Known Issues: known_issues.md
- Coming Soon: coming_soon.md
- Contributors: contributors.md
