site_name: Simnibs Cifti Tools 
theme: 
  name: material
  features:
    # - navigation.tabs       # Adds top-level navigation tabs
    - navigation.sections   # Group navigation into sections
    - content.code.copy     # Adds a copy button to code blocks
    # - navigation.expand     # Optional: Keeps the sidebar sections expanded by default

plugins:
  - search

markdown_extensions:
  # Standard extensions for essential formatting
  - admonition          # Required for !!! note "Title" blocks
  - attr_list           # Allows adding CSS classes/styles to Markdown
  - def_list            # Support for definition lists
  - footnotes           # Support for [^1] style footnotes
  - md_in_html          # Allows Markdown inside <div> or other HTML tags
  - toc:
      permalink: true   # Adds clickable anchor links next to headers

  # PyMdown Extensions for advanced technical features
  - pymdownx.highlight: # Superior code syntax highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite: # Highlighting for `inline code`
  - pymdownx.superfences: # Allows nesting and Mermaid diagrams
  - pymdownx.tabbed:      # Required for [Content Tabs]
      alternate_style: true
  - pymdownx.tasklist:    # Required for - [x] task checkboxes
      custom_checkbox: true
  - pymdownx.emoji:       # Support for :material-account: icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Overview: project_overview.md 
  - Installation: Installation.md 
  - Quickstart Guide: quickstart_guide.md
  - Users Guide: args_flags.md
  - Outputs: Outputs.md
  - Modularized Tools: Utilities.md 
  - Tutorials: default_example.md
  - Troubleshooting: troubleshooting.md
  - Contributors: contributors.md

  # - Required Imaging Files: dependancies.md
  # - Usage: useage.md
  # - Efield Generator: Efield_generator.md
  # - FAQ: FAQ.md
  # - Coming Soon: coming_soon.md
 

